### PR TITLE
BE-initial-commit

### PR DESCRIPTION
**Pull request by evcyen**
initial commit for post and get requests of votes, including creation of candidate, voter, and vote model, as well as candidate and vote resources

### CODE REVIEW

**Comment by sophyphreak** [comment]
Hey @thearchitectsnotebook, this is great. I know it would take apart a lot of what you did, but I recommend breaking this down into just one resource and one model. Make it really simple--we can scale it up later. 

I would say the one resource should be Vote and the one model should be Candidate. To keep it simple for now, take in the candidate's name. 

GET Vote should just return a json with a list of all candidate's names and vote totals.

POST Vote should try to find the candidate name in the database. If not found, add the candidate and start their total at 1. If found, increment the candidate's total by one.

Other things:
- make sure to import `from db.db import db` since the `db.py` is inside a `db` folder.
- make sure to do `.add_resource` in `app.py`. This is what will allow you to test this in Postman.
- make sure to pass `self` as the first argument in `__init__`.

I'm going to try to keep my personal computer on tomorrow, so please reach out if you want to ask any questions or do some peer programming.

**Comment by evcyen** [comment]
@sophyphreak Thanks for all the comments and suggestions! Will make another commit by this evening

**Comment by evcyen** [comment]
Hi, second commit! Although the GET request is working as expected, I'm receiving a missing argument error for the POST request. I included the parameter "candidate_name": "Test Name" in Postman, but it still gives me the same error. Let me know if you have any insight as to why - in the meantime, I'll keep working on it.

```
File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\ecwin\.virtualenvs\v24-bears-team-04-glPhUZye\Lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: post() missing 1 required positional argument: 'candidate_name'
127.0.0.1 - - [20/Oct/2020 18:10:15] "GET /?candidate_name=Harry%20Potter HTTP/1.1" 200 -
```

**Comment by sophyphreak** [comment]
I was able to fix POST. The problem was mostly that the argument needs to be parsed before it's available inside the post method. I also altered the Vote endpoint to be `/api/vote`, which is a more standard form.

Great job! Thank you for doing that

**Pull request merged**
